repository: https://github.com/r-trigo/rt-jekyll-website

name: Rui Trigo Jeksite
title: A DevOps Jekyll Website
email: ruimigueltrigo@gmail.com
description: >-
  Welcome to Rui Trigo Jekyll Website. Here you can find my writing work as well as professional info about me.

github_username:  r-trigo
instagram_username: ru1tr1go
linkedin_username:  r-trigo
stackoverflow_username: "6460173"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/images/profile.jpg
about_content: |
  Computer engineer and Mobile Computing master.
  Graduated from Escola Superior de Tecnologia e Gestão of Instituto Politécnico da Guarda.
  Cisco certified network associate (CCNA and CCNA Security) and Linux certified (Linux essentials and LPIC-1).
  Passioned by martial arts and using technology in order to improve the world.
  Also loves a good get-together. Computer experience started in 2009.

  Check out my easy reading [JSON resume](https://registry.jsonresume.org/r-trigo) to see my academic background, work experience and other interests.
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: What I Do

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: My Interests
more_content: |
  Martial Arts  |  Fitness  |  Reading  |  IoT
# Footer
footer_show_references: false

# Build settings
#theme: minima
theme: modern-resume-theme
darkmode: false
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
