repository: https://github.com/r-trigo/jekyll-blog

name: Jekyll Blog
title: A DevOps Blog
email: ruimigueltrigo[at]gmail.com
description: >-
  Welcome to my Jekyll Blog. Here you can find my writing work as well as professional info about me.

dev_username: rtrigo
github_username:  r-trigo
gitlab_username:  rtrigo
instagram_username: ru1tr1go
linkedin_username:  r-trigo
stackoverflow_username: "6460173"
twitter_username: "ru1tr1go"

# comment for local development
domain: r-trigo.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://r-trigo.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /jekyll-blog/          # place folder name if the site is served in a subfolder

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/images/profile.jpg
about_content: |
  Computer engineer and Mobile Computing master.
  Graduated from Escola Superior de Tecnologia e Gestão of Instituto Politécnico da Guarda.
  AWS (CCP), Cisco (CCNA and CCNA Security), Hashicorp (Terraform Associate), Kubernetes (CKA) and Linux certified (Linux essentials and LPIC-1).
  Passioned by martial arts and using technology in order to improve the world.
  Also loves a good get-together. Computer experience started in 2009.

  Check out my easy reading [JSON resume](https://registry.jsonresume.org/r-trigo) to see my academic background, work experience and other interests.
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
experience_title: What I Do

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: My Interests
more_content: |
  Martial Arts  |  Non-fiction books  |  HomeLabbing
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/modern-resume-theme
darkmode: false
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
